plugins {
    id 'com.android.application'
}

def cmflixAppKey =
        System.getenv("CMFLIX_APP_KEY")
                ?: project.findProperty("CMFLIX_APP_KEY")
                ?: ""

android {
    namespace 'com.cmflix.nativeapp'
    compileSdk 36

    defaultConfig {
        applicationId "com.cmflix.nativeapp"

        minSdk 23
        targetSdk 35

        versionCode 3
        versionName "1.2"

        buildConfigField(
                "String",
                "CMFLIX_APP_KEY",
                "\"${cmflixAppKey.replace("\\", "\\\\").replace("\"", "\\\"")}\""
        )

        buildConfigField(
                "String",
                "API_BASE_URL",
                "\"https://kkflix.xubi.org/api/\""
        )
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        debug {
            minifyEnabled false
        }

        release {
            minifyEnabled true
            shrinkResources true

            proguardFiles(
                    getDefaultProguardFile(
                            'proguard-android-optimize.txt'
                    ),
                    'proguard-rules.pro'
            )
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.activity:activity:1.11.0'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.core:core-splashscreen:1.0.0'

    def media3Version = "1.11.0"

    implementation "androidx.media3:media3-exoplayer:$media3Version"
    implementation "androidx.media3:media3-exoplayer-hls:$media3Version"
    implementation "androidx.media3:media3-ui:$media3Version"

    implementation 'com.github.bumptech.glide:glide:4.16.0'
}
