// CM FLIX native secret store.
//
// The AES key material lives here in compiled ARM machine code instead of
// in the dex file, so plain dex string inspection (MT Manager, jadx, ...)
// cannot reveal it. The four key parts are additionally XOR-masked so that
// even a raw `strings` pass over the .so file shows nothing useful.
//
// Security note: this raises the bar from "dex reader" to "native reverser"
// (IDA/Ghidra + ARM). A native anti-tamper gate (debugger / Frida /
// signature verification) additionally fails closed on re-signed or
// instrumented copies. It does not make client-side secrets unrecoverable;
// nothing can, as long as the app itself must decrypt them offline.

#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef __ANDROID__
#include <jni.h>
#endif

// ---------------------------------------------------------------------------
// SHA-256 (public-domain style implementation)
// ---------------------------------------------------------------------------

#include "sha256_tables.inc"  // K[64], H0[8] generated by script, verified

#define ROTR(x, n) (((x) >> (n)) | ((x) << (32 - (n))))

static void sha256_block(const uint8_t *p, uint32_t h[8]) {
    uint32_t w[64];
    for (int i = 0; i < 16; i++) {
        w[i] = ((uint32_t)p[i * 4] << 24) | ((uint32_t)p[i * 4 + 1] << 16) |
               ((uint32_t)p[i * 4 + 2] << 8) | (uint32_t)p[i * 4 + 3];
    }
    for (int i = 16; i < 64; i++) {
        uint32_t s0 = ROTR(w[i - 15], 7) ^ ROTR(w[i - 15], 18) ^ (w[i - 15] >> 3);
        uint32_t s1 = ROTR(w[i - 2], 17) ^ ROTR(w[i - 2], 19) ^ (w[i - 2] >> 10);
        w[i] = w[i - 16] + s0 + w[i - 7] + s1;
    }
    uint32_t a = h[0], b = h[1], c = h[2], d = h[3];
    uint32_t e = h[4], f = h[5], g = h[6], hh = h[7];
    for (int i = 0; i < 64; i++) {
        uint32_t S1 = ROTR(e, 6) ^ ROTR(e, 11) ^ ROTR(e, 25);
        uint32_t ch = (e & f) ^ (~e & g);
        uint32_t t1 = hh + S1 + ch + K[i] + w[i];
        uint32_t S0 = ROTR(a, 2) ^ ROTR(a, 13) ^ ROTR(a, 22);
        uint32_t maj = (a & b) ^ (a & c) ^ (b & c);
        uint32_t t2 = S0 + maj;
        hh = g; g = f; f = e; e = d + t1;
        d = c; c = b; b = a; a = t1 + t2;
    }
    h[0] += a; h[1] += b; h[2] += c; h[3] += d;
    h[4] += e; h[5] += f; h[6] += g; h[7] += hh;
}

static void sha256(const uint8_t *msg, size_t len, uint8_t out[32]) {
    uint32_t h[8];
    memcpy(h, H0, sizeof(h));
    uint8_t block[64];
    size_t off = 0;
    uint64_t bitlen = (uint64_t)len * 8;
    while (len - off >= 64) {
        sha256_block(msg + off, h);
        off += 64;
    }
    size_t rem = len - off;
    memcpy(block, msg + off, rem);
    block[rem++] = 0x80;
    if (rem > 56) {
        memset(block + rem, 0, 64 - rem);
        sha256_block(block, h);
        rem = 0;
    }
    memset(block + rem, 0, 56 - rem);
    for (int i = 0; i < 8; i++) {
        block[56 + i] = (uint8_t)(bitlen >> (56 - i * 8));
    }
    sha256_block(block, h);
    for (int i = 0; i < 8; i++) {
        out[i * 4] = (uint8_t)(h[i] >> 24);
        out[i * 4 + 1] = (uint8_t)(h[i] >> 16);
        out[i * 4 + 2] = (uint8_t)(h[i] >> 8);
        out[i * 4 + 3] = (uint8_t)h[i];
    }
}

// ---------------------------------------------------------------------------
// AES-128 decrypt (inverse cipher). S-box is computed at startup from the
// GF(2^8) definition so no 256-byte tables need to be transcribed.
// ---------------------------------------------------------------------------

static uint8_t gf_mul(uint8_t a, uint8_t b) {
    uint8_t r = 0;
    while (b) {
        if (b & 1) r ^= a;
        uint8_t hi = a & 0x80;
        a <<= 1;
        if (hi) a ^= 0x1b;
        b >>= 1;
    }
    return r;
}

static uint8_t gf_inv(uint8_t x) {
    if (x == 0) return 0;
    uint8_t r = 1, base = x;
    uint16_t e = 254;
    while (e) {
        if (e & 1) r = gf_mul(r, base);
        base = gf_mul(base, base);
        e >>= 1;
    }
    return r;
}

static uint8_t sbox[256];
static uint8_t rsbox[256];
static int sbox_ready = 0;

static void sbox_init(void) {
    if (sbox_ready) return;
    for (int i = 0; i < 256; i++) {
        uint8_t inv = gf_inv((uint8_t)i);
        uint8_t s = inv ^ (uint8_t)((inv << 1) | (inv >> 7))
                        ^ (uint8_t)((inv << 2) | (inv >> 6))
                        ^ (uint8_t)((inv << 3) | (inv >> 5))
                        ^ (uint8_t)((inv << 4) | (inv >> 4)) ^ 0x63;
        sbox[i] = s;
        rsbox[s] = (uint8_t)i;
    }
    sbox_ready = 1;
}

static uint32_t rcon_for(int i) {
    uint8_t r = 1;
    for (int k = 1; k < i; k++) r = gf_mul(r, 2);
    return (uint32_t)r << 24;
}

static void aes128_keyexpand(const uint8_t key[16], uint8_t rk[11][16]) {
    uint32_t w[44];
    for (int i = 0; i < 4; i++) {
        w[i] = ((uint32_t)key[i * 4] << 24) | ((uint32_t)key[i * 4 + 1] << 16) |
               ((uint32_t)key[i * 4 + 2] << 8) | key[i * 4 + 3];
    }
    sbox_init();
    for (int i = 4; i < 44; i++) {
        uint32_t t = w[i - 1];
        if (i % 4 == 0) {
            t = (t << 8) | (t >> 24);  // RotWord
            t = ((uint32_t)sbox[(t >> 24) & 0xff] << 24) |
                ((uint32_t)sbox[(t >> 16) & 0xff] << 16) |
                ((uint32_t)sbox[(t >> 8) & 0xff] << 8) |
                (uint32_t)sbox[t & 0xff];  // SubWord
            t ^= rcon_for(i / 4);
        }
        w[i] = w[i - 4] ^ t;
    }
    for (int r = 0; r < 11; r++) {
        for (int i = 0; i < 4; i++) {
            rk[r][i * 4] = (uint8_t)(w[r * 4 + i] >> 24);
            rk[r][i * 4 + 1] = (uint8_t)(w[r * 4 + i] >> 16);
            rk[r][i * 4 + 2] = (uint8_t)(w[r * 4 + i] >> 8);
            rk[r][i * 4 + 3] = (uint8_t)w[r * 4 + i];
        }
    }
}

static void add_round_key(uint8_t s[16], const uint8_t rk[16]) {
    for (int i = 0; i < 16; i++) s[i] ^= rk[i];
}

static void inv_shift_rows(uint8_t s[16]) {
    uint8_t t[16];
    for (int row = 0; row < 4; row++) {
        for (int col = 0; col < 4; col++) {
            t[row + 4 * col] = s[row + 4 * ((col - row + 4) % 4)];
        }
    }
    memcpy(s, t, 16);
}

static void inv_sub_bytes(uint8_t s[16]) {
    for (int i = 0; i < 16; i++) s[i] = rsbox[s[i]];
}

static void inv_mix_columns(uint8_t s[16]) {
    for (int c = 0; c < 4; c++) {
        uint8_t a0 = s[c * 4], a1 = s[c * 4 + 1], a2 = s[c * 4 + 2], a3 = s[c * 4 + 3];
        s[c * 4]     = gf_mul(a0, 0x0e) ^ gf_mul(a1, 0x0b) ^ gf_mul(a2, 0x0d) ^ gf_mul(a3, 0x09);
        s[c * 4 + 1] = gf_mul(a0, 0x09) ^ gf_mul(a1, 0x0e) ^ gf_mul(a2, 0x0b) ^ gf_mul(a3, 0x0d);
        s[c * 4 + 2] = gf_mul(a0, 0x0d) ^ gf_mul(a1, 0x09) ^ gf_mul(a2, 0x0e) ^ gf_mul(a3, 0x0b);
        s[c * 4 + 3] = gf_mul(a0, 0x0b) ^ gf_mul(a1, 0x0d) ^ gf_mul(a2, 0x09) ^ gf_mul(a3, 0x0e);
    }
}

static void aes128_ecb_decrypt_block(const uint8_t in[16], uint8_t out[16],
                                     uint8_t rk[11][16]) {
    uint8_t s[16];
    memcpy(s, in, 16);
    add_round_key(s, rk[10]);
    for (int round = 9; round >= 1; round--) {
        inv_shift_rows(s);
        inv_sub_bytes(s);
        add_round_key(s, rk[round]);
        inv_mix_columns(s);
    }
    inv_shift_rows(s);
    inv_sub_bytes(s);
    add_round_key(s, rk[0]);
    memcpy(out, s, 16);
}

// ---------------------------------------------------------------------------
// Key derivation + AES-128-CBC decrypt, mirroring the Gradle build-time
// encryption exactly: key = SHA256(parts+"|k1")[:16],
// iv = SHA256(parts+"|i1")[:16], parts = P2+P0+P3+P1.
// ---------------------------------------------------------------------------

// XOR-masked key parts. The mask is deliberately NOT a compile-time
// constant: it is read through a volatile, which forces the unmasking loop
// to execute at runtime. Otherwise the optimizer constant-folds the XOR
// and stores the assembled secret as plaintext in .rodata (verified via
// `strings` on the built .so). Assembly order below is P2+P0+P3+P1.
static uint8_t xor_mask(void) {
    static volatile uint8_t m = 0x5A;
    return m;
}
static const uint8_t P2M[] = {0x14,0x1f,0x2f,0x33,0x17,0x34,0x3d,0x02,0x3c,0x02};
static const uint8_t P0M[] = {0x20,0x35,0x0e,0x15,0x18,0x6d,0x1b,0x33,0x3e,0x0a};
static const uint8_t P3M[] = {0x3c,0x00,0x0f,0x36,0x62,0x3f,0x23,0x23,0x1e,0x1e};
static const uint8_t P1M[] = {0x2b,0x22,0x17,0x69,0x6b,0x28,0x69,0x19,0x1e,0x2e};

static void derive_key_iv(uint8_t key[16], uint8_t iv[16]) {
    char parts[41];
    const uint8_t *ms[4] = {P2M, P0M, P3M, P1M};
    const uint8_t xm = xor_mask();
    int o = 0;
    for (int k = 0; k < 4; k++) {
        for (int i = 0; i < 10; i++) parts[o++] = (char)(ms[k][i] ^ xm);
    }
    parts[40] = '\0';
    uint8_t digest[32];
    char buf[48];
    memcpy(buf, parts, 40);
    memcpy(buf + 40, "|k1", 3);
    sha256((const uint8_t *)buf, 43, digest);
    memcpy(key, digest, 16);
    memcpy(buf + 40, "|i1", 3);
    sha256((const uint8_t *)buf, 43, digest);
    memcpy(iv, digest, 16);
    memset(parts, 0, sizeof(parts));
    memset(buf, 0, sizeof(buf));
    memset(digest, 0, sizeof(digest));
}

// Returns malloc'd NUL-terminated plaintext, or NULL on any failure.
// Caller frees with free(). Never returns partial/garbage data.
static char *secrets_decrypt(const uint8_t *ct, size_t ct_len, size_t *out_len) {
    if (ct == NULL || out_len == NULL) return NULL;
    if (ct_len == 0 || ct_len % 16 != 0) return NULL;

    uint8_t key[16], iv[16];
    derive_key_iv(key, iv);

    uint8_t rk[11][16];
    aes128_keyexpand(key, rk);
    memset(key, 0, sizeof(key));

    uint8_t *pt = (uint8_t *)malloc(ct_len + 1);
    if (!pt) { memset(iv, 0, sizeof(iv)); return NULL; }

    uint8_t prev[16], blk[16], dec[16];
    memcpy(prev, iv, 16);
    for (size_t b = 0; b < ct_len; b += 16) {
        memcpy(blk, ct + b, 16);
        aes128_ecb_decrypt_block(blk, dec, rk);
        for (int i = 0; i < 16; i++) pt[b + i] = dec[i] ^ prev[i];
        memcpy(prev, blk, 16);
    }
    memset(iv, 0, sizeof(iv));
    memset(prev, 0, sizeof(prev));
    memset(dec, 0, sizeof(dec));
    memset(blk, 0, sizeof(blk));
    memset(rk, 0, sizeof(rk));

    // PKCS#7 unpad with validation
    uint8_t pad = pt[ct_len - 1];
    int ok = (pad >= 1 && pad <= 16 && pad <= ct_len);
    uint8_t bad = 0;
    for (size_t i = 0; i < ct_len; i++) {
        uint8_t in_pad = (i >= ct_len - (ok ? pad : 0)) ? 1 : 0;
        bad |= in_pad & (uint8_t)(pt[i] ^ pad);
    }
    if (!ok || bad) { memset(pt, 0, ct_len); free(pt); return NULL; }
    size_t plen = ct_len - pad;
    pt[plen] = '\0';
    *out_len = plen;
    return (char *)pt;
}

#ifdef __ANDROID__
// ---------------------------------------------------------------------------
// Anti-tamper: debugger / Frida / signature verification.
//
// Runs natively before any secret is decrypted. ANY failure fails closed:
// the JNI entry returns NULL (CryptoUtil.dec -> ""), so a re-signed/cloned
// APK, a debugger-attached session, or a Frida-instrumented process can
// never obtain decrypted secrets. This raises the bar from "repackage the
// APK" to "defeat native checks at runtime".
//
// NOTE: root detection is implemented but intentionally NOT enforced:
// blocking rooted devices would lock out legitimate users, and clone /
// re-sign protection is fully covered by the signature check below.
// ---------------------------------------------------------------------------

#include <unistd.h>
#include <stdio.h>

// DIAG BUILD ONLY: records which anti-tamper check failed so a startup
// toast can report it. Never shipped in release builds.
static char tamper_detail[48] = "not-run";
static void set_tamper_detail(const char *s) {
    size_t n = strlen(s);
    if (n > sizeof(tamper_detail) - 1) n = sizeof(tamper_detail) - 1;
    memcpy(tamper_detail, s, n);
    tamper_detail[n] = '\0';
}

// Expected release signing-cert SHA-256, XOR-masked with the same volatile
// mask as the key parts (keeps `strings` output clean; the fingerprint
// itself is public, but no need to advertise it).
// Fingerprint verified 2026-10-01 from the shipped release APK.
// WARNING: rotating the release keystore requires updating this hash,
// otherwise the app will fail closed (no secrets) on the new signature.
static const uint8_t CERT_HASH_M[] = {0x76,0x70,0x45,0x44,0xe5,0x20,0x88,0xf9,0xb0,0xfc,0x66,0xc9,0x2c,0x8e,0xb3,0x51,0x36,0x9a,0x23,0x99,0xa8,0x7f,0x7f,0x14,0xd4,0x37,0x22,0x71,0xbc,0xb2,0x5b,0x8e};

// 1 if a debugger is tracing us.
//
// Passive check only: reads TracerPid from /proc/self/status. The old
// ptrace(PTRACE_TRACEME) probe was removed because it false-positived on
// stock devices (the platform can refuse ptrace for apps), which bricked
// legit installs — fail-closed on a flaky probe is worse than no probe.
// TracerPid is non-zero if and only if a tracer is really attached.
static int tamper_debugger(void) {
    FILE *f = fopen("/proc/self/status", "r");
    int traced = 0;
    if (f) {
        char line[256];
        while (fgets(line, sizeof(line), f)) {
            if (strncmp(line, "TracerPid:", 10) == 0) {
                traced = (atoi(line + 10) != 0);
                break;
            }
        }
        fclose(f);
    }
    return traced;
}

// 1 if Frida (or a similar injector) is mapped into our process.
static int tamper_frida(void) {
    FILE *f = fopen("/proc/self/maps", "r");
    if (!f) return 0;
    char line[512];
    int found = 0;
    while (fgets(line, sizeof(line), f)) {
        for (char *p = line; *p; p++) {
            if (*p >= 'A' && *p <= 'Z') *p = (char)(*p + 32);
        }
        if (strstr(line, "frida") || strstr(line, "gum-js")) { found = 1; break; }
    }
    fclose(f);
    return found;
}

// 1 if the device looks rooted. Informational only — not enforced (see note).
static int tamper_rooted(void) {
    static const char *paths[] = {
        "/system/bin/su", "/system/xbin/su", "/sbin/su",
        "/su/bin/su", "/data/local/xbin/su",
        "/system/app/Superuser.apk", "/system/app/SuperSU.apk",
        NULL
    };
    for (int i = 0; paths[i]; i++) {
        if (access(paths[i], F_OK) == 0) return 1;
    }
    return 0;
}

// SHA-256 of our own signing certificate, compared against CERT_HASH_M.
// Returns 1 only when the APK signature matches the release key — i.e. the
// APK was NOT re-signed/cloned (MT Manager clone & re-sign change it).
static int tamper_signature_ok(JNIEnv *env) {
    int ok = 0;
    jobject app = NULL, pm = NULL, pkgName = NULL, info = NULL;
    jobjectArray signers = NULL;
    jobject sig0 = NULL;
    jclass at = NULL, appCls = NULL, pmCls = NULL, piCls = NULL;
    jclass siCls = NULL, sigCls = NULL;
    jmethodID curApp = NULL, getPM = NULL, getPkg = NULL, getPI = NULL;
    jmethodID getSigners = NULL, toBA = NULL;
    jfieldID fSI = NULL, fS = NULL;
    jobject si = NULL;
    jbyteArray certBytes = NULL;
    jsize clen = 0;
    jbyte *cbytes = NULL;
    uint8_t digest[32];
    uint8_t xm = 0;
    uint8_t diff = 0;

    set_tamper_detail("sig:fail"); // DIAG: refined below on specific outcomes.
    at = env->FindClass("android/app/ActivityThread");
    if (at == NULL) goto done;
    curApp = env->GetStaticMethodID(at, "currentApplication",
                                    "()Landroid/app/Application;");
    if (curApp == NULL) goto done;
    app = env->CallStaticObjectMethod(at, curApp);
    if (app == NULL || env->ExceptionCheck()) {
        set_tamper_detail("sig:context"); // DIAG
        goto done;
    }

    appCls = env->GetObjectClass(app);
    getPM = env->GetMethodID(appCls, "getPackageManager",
                             "()Landroid/content/pm/PackageManager;");
    getPkg = env->GetMethodID(appCls, "getPackageName",
                              "()Ljava/lang/String;");
    if (getPM == NULL || getPkg == NULL) goto done;
    pm = env->CallObjectMethod(app, getPM);
    pkgName = env->CallObjectMethod(app, getPkg);
    if (pm == NULL || pkgName == NULL || env->ExceptionCheck()) goto done;

    pmCls = env->GetObjectClass(pm);
    getPI = env->GetMethodID(pmCls, "getPackageInfo",
        "(Ljava/lang/String;I)Landroid/content/pm/PackageInfo;");
    if (getPI == NULL) goto done;

    // Prefer GET_SIGNING_CERTIFICATES (API 28+), fall back to GET_SIGNATURES.
    info = env->CallObjectMethod(pm, getPI, pkgName, 0x08000000);
    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        info = env->CallObjectMethod(pm, getPI, pkgName, 0x40);
    }
    if (env->ExceptionCheck() || info == NULL) goto done;

    piCls = env->GetObjectClass(info);
    fSI = env->GetFieldID(piCls, "signingInfo",
                          "Landroid/content/pm/SigningInfo;");
    if (fSI != NULL && !env->ExceptionCheck()) {
        si = env->GetObjectField(info, fSI);
        if (si != NULL && !env->ExceptionCheck()) {
            siCls = env->GetObjectClass(si);
            getSigners = env->GetMethodID(siCls, "getApkContentsSigners",
                "()[Landroid/content/pm/Signature;");
            if (getSigners != NULL && !env->ExceptionCheck()) {
                signers = (jobjectArray)env->CallObjectMethod(si, getSigners);
            }
        }
    }
    if (env->ExceptionCheck()) env->ExceptionClear();
    if (signers == NULL) {
        // Pre-28 path: PackageInfo.signatures
        fS = env->GetFieldID(piCls, "signatures",
                             "[Landroid/content/pm/Signature;");
        if (fS != NULL && !env->ExceptionCheck()) {
            signers = (jobjectArray)env->GetObjectField(info, fS);
        }
        if (env->ExceptionCheck()) env->ExceptionClear();
    }
    if (signers == NULL || env->GetArrayLength(signers) < 1) goto done;

    sig0 = env->GetObjectArrayElement(signers, 0);
    if (sig0 == NULL) goto done;
    sigCls = env->GetObjectClass(sig0);
    toBA = env->GetMethodID(sigCls, "toByteArray", "()[B");
    if (toBA != NULL && !env->ExceptionCheck()) {
        certBytes = (jbyteArray)env->CallObjectMethod(sig0, toBA);
    }
    if (certBytes == NULL || env->ExceptionCheck()) goto done;

    clen = env->GetArrayLength(certBytes);
    cbytes = env->GetByteArrayElements(certBytes, NULL);
    if (cbytes == NULL) goto done;

    sha256((const uint8_t *)cbytes, (size_t)clen, digest);
    env->ReleaseByteArrayElements(certBytes, cbytes, JNI_ABORT);

    // constant-time compare against the unmasked expected hash
    xm = xor_mask();
    for (int i = 0; i < 32; i++) {
        diff |= (uint8_t)(digest[i] ^ (CERT_HASH_M[i] ^ xm));
    }
    memset(digest, 0, sizeof(digest));
    ok = (diff == 0);
    if (!ok) set_tamper_detail("sig:mismatch"); // DIAG

done:
    if (env->ExceptionCheck()) env->ExceptionClear();
    return ok;
}

// Combined environment gate. Evaluated once, then cached.
static int tamper_env_ok(JNIEnv *env) {
    static int cached = -1;
    if (cached != -1) return cached;
    int ok = 1;
    // DIAG: first failure wins for the detail string.
    if (tamper_debugger()) { ok = 0; set_tamper_detail("debugger"); }
    else if (tamper_frida()) { ok = 0; set_tamper_detail("frida"); }
    else if (!tamper_signature_ok(env)) { ok = 0; /* detail set inside */ }
    else { set_tamper_detail("ok"); }
    // Root is detected but not enforced (see note above).
    (void)tamper_rooted();
    cached = ok;
    return ok;
}

#endif  // __ANDROID__

#ifdef __ANDROID__
// JNI bridge: com.cmflix.nativeapp.CryptoUtil.nativeDec(byte[])
extern "C" __attribute__((visibility("default")))
jstring Java_com_cmflix_nativeapp_CryptoUtil_nativeDec(JNIEnv *env, jclass,
                                                      jbyteArray ctArr) {
    // Anti-tamper gate: re-signed/cloned APK, debugger, or Frida -> fail
    // closed (NULL), so no secret is ever decrypted in a tampered process.
    if (!tamper_env_ok(env)) return NULL;
    if (ctArr == NULL) return NULL;
    jsize len = env->GetArrayLength(ctArr);
    if (len <= 0 || len % 16 != 0) return NULL;
    jbyte *bytes = env->GetByteArrayElements(ctArr, NULL);
    if (bytes == NULL) return NULL;
    size_t out_len = 0;
    char *pt = secrets_decrypt((const uint8_t *)bytes, (size_t)len, &out_len);
    env->ReleaseByteArrayElements(ctArr, bytes, JNI_ABORT);
    if (pt == NULL) return NULL;
    jstring res = env->NewStringUTF(pt);
    memset(pt, 0, out_len);
    free(pt);
    return res;
}

// DIAG BUILD ONLY: returns the anti-tamper gate detail ("ok", "debugger",
// "frida", "sig:context", "sig:fail", "sig:mismatch"). Never in release.
extern "C" __attribute__((visibility("default")))
jstring Java_com_cmflix_nativeapp_CryptoUtil_tamperStatus(JNIEnv *env, jclass) {
    tamper_env_ok(env); // ensure the gate has been evaluated at least once
    return env->NewStringUTF(tamper_detail);
}
#endif

// Local test harness (compiled with -DSECRETS_TEST on x86_64).
#ifdef SECRETS_TEST
#include <stdio.h>

static int b64val(char c) {
    if (c >= 'A' && c <= 'Z') return c - 'A';
    if (c >= 'a' && c <= 'z') return c - 'a' + 26;
    if (c >= '0' && c <= '9') return c - '0' + 52;
    if (c == '+') return 62;
    if (c == '/') return 63;
    return -1;
}

static uint8_t *b64dec(const char *s, size_t *out_len) {
    size_t full = strlen(s);
    size_t len = (full / 4) * 3;
    if (full >= 1 && s[full - 1] == '=') len--;
    if (full >= 2 && s[full - 2] == '=') len--;
    uint8_t *out = (uint8_t *)malloc(len + 1);
    size_t o = 0;
    for (size_t i = 0; i < full; i += 4) {
        int c0 = b64val(s[i]);
        int c1 = b64val(s[i + 1]);
        int c2 = s[i + 2] == '=' ? 0 : b64val(s[i + 2]);
        int c3 = s[i + 3] == '=' ? 0 : b64val(s[i + 3]);
        int v = (c0 << 18) | (c1 << 12) | (c2 << 6) | c3;
        if (o < len) out[o++] = (uint8_t)((v >> 16) & 0xff);
        if (o < len) out[o++] = (uint8_t)((v >> 8) & 0xff);
        if (o < len) out[o++] = (uint8_t)(v & 0xff);
    }
    *out_len = len;
    return out;
}

int main(void) {
    struct { const char *ct; const char *want; const char *name; } tv[] = {
#include "test_vectors.inc"
    };
    int fails = 0;
    for (size_t t = 0; t < sizeof(tv) / sizeof(tv[0]); t++) {
        size_t clen = 0;
        uint8_t *ct = b64dec(tv[t].ct, &clen);
        size_t olen = 0;
        char *pt = secrets_decrypt(ct, clen, &olen);
        free(ct);
        int ok = pt && strcmp(pt, tv[t].want) == 0;
        printf("[%s] %-9s -> %s\n", ok ? "PASS" : "FAIL", tv[t].name,
               ok ? pt : "(decrypt failed)");
        if (!ok) fails++;
        if (pt) { memset(pt, 0, olen); free(pt); }
    }
    {
        size_t olen = 0;
        uint8_t garbage[16] = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16};
        char *r1 = secrets_decrypt(garbage, 16, &olen);
        uint8_t odd[20] = {0};
        char *r2 = secrets_decrypt(odd, 20, &olen);
        char *r3 = secrets_decrypt(NULL, 0, &olen);
        int ok = (r1 == NULL && r2 == NULL && r3 == NULL);
        printf("[%s] fail-closed negatives\n", ok ? "PASS" : "FAIL");
        if (!ok) fails++;
    }
    printf(fails ? "RESULT: %d FAILURES\n" : "RESULT: ALL PASS\n", fails);
    return fails ? 1 : 0;
}
#endif
